In [37]:
import pandas as pd
import pylab
import scipy.stats
import numpy as np
from numpy.linalg import inv
import sklearn
from matplotlib.mlab import PCA

In [15]:
t=pd.read_csv('/Users/thiamang/Documents/github/personal/python/models/mvdata/T8-4.dat', sep='\s+', header=None, skiprows=0);
t=t.rename(columns={0:'jp_morgan', 1:'citibank', 2:'wells_fargo', 3:'royal', 4:'exxon'});

In [30]:
cov_t=np.cov(t)

In [31]:
inv_cov_t=np.linalg.inv(cov_t)

In [32]:
inv_cov_t

array([[ -7.92193353e+18,   3.16817351e+19,  -9.03810102e+18, ...,
          2.70069764e+18,   3.02351251e+19,  -3.38636519e+19],
       [ -5.53712995e+18,   1.18748779e+20,  -6.55692760e+19, ...,
          1.57840728e+19,   1.11341733e+20,  -5.13314168e+19],
       [  1.75143240e+17,   7.09626384e+19,  -2.76878854e+19, ...,
          6.95068312e+18,   5.14299655e+19,  -6.31357060e+19],
       ..., 
       [  1.63597601e+18,  -1.53946310e+19,   5.10695877e+18, ...,
         -5.32486732e+18,  -2.29595270e+19,   1.81136238e+19],
       [  2.11819110e+18,  -2.02219123e+19,   1.34346561e+19, ...,
         -4.39461396e+18,  -2.23514261e+19,   2.67792526e+19],
       [  9.98770287e+18,  -1.84392644e+20,   9.40135089e+19, ...,
         -2.78429206e+19,  -1.70590925e+20,   1.13929294e+20]])

In [33]:
w,v = np.linalg.eig(inv_cov_t);

In [35]:
v

array([[-0.06592505+0.j        , -0.04872117-0.02257767j,
        -0.04872117+0.02257767j, ...,  0.19529971-0.03101101j,
        -0.16455780+0.j        ,  0.05473112+0.j        ],
       [-0.21256432+0.j        , -0.26912378+0.01921833j,
        -0.26912378-0.01921833j, ...,  0.01941056+0.02303749j,
        -0.07445102+0.j        , -0.13286549+0.j        ],
       [-0.00235092+0.j        , -0.17521049+0.05517797j,
        -0.17521049-0.05517797j, ..., -0.06352166+0.01635324j,
         0.07298146+0.j        ,  0.10039503+0.j        ],
       ..., 
       [ 0.00890966+0.j        ,  0.03687938+0.01036996j,
         0.03687938-0.01036996j, ...,  0.02330058-0.04391007j,
        -0.04064772+0.j        ,  0.07412048+0.j        ],
       [ 0.02017725+0.j        ,  0.04194548+0.00955367j,
         0.04194548-0.00955367j, ..., -0.03176445-0.05042822j,
         0.05887951+0.j        ,  0.04869109+0.j        ],
       [ 0.35478656+0.j        ,  0.34171127+0.j        ,
         0.34171127-0.j      

In [36]:
w

array([ -2.27926823e+20 +0.00000000e+00j,
         9.03312656e+19 +1.52608732e+20j,
         9.03312656e+19 -1.52608732e+20j,
        -5.36114240e+19 +4.91059423e+19j,
        -5.36114240e+19 -4.91059423e+19j,
        -6.23371259e+19 +0.00000000e+00j,
         6.70048983e+19 +0.00000000e+00j,
         4.64722591e+19 +3.63153682e+19j,
         4.64722591e+19 -3.63153682e+19j,
        -8.48053444e+18 +5.21616972e+19j,
        -8.48053444e+18 -5.21616972e+19j,
        -3.24723816e+19 +0.00000000e+00j,
         2.86537238e+19 +9.19508181e+18j,
         2.86537238e+19 -9.19508181e+18j,
         1.84590569e+19 +1.75190963e+19j,
         1.84590569e+19 -1.75190963e+19j,
        -2.42049573e+19 +0.00000000e+00j,
        -2.04915982e+19 +9.91028595e+18j,
        -2.04915982e+19 -9.91028595e+18j,
         2.36116925e+19 +6.30094510e+17j,
         2.36116925e+19 -6.30094510e+17j,
         4.49238890e+18 +2.15615178e+19j,
         4.49238890e+18 -2.15615178e+19j,
        -1.01514999e+19 +1.8445652

In [49]:
results=PCA(t,standardize=True)

In [50]:
results

In [51]:
print results

In [52]:
dir(results)

['Wt',
 'Y',
 '__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_colinear',
 'a',
 'center',
 'fracs',
 'mu',
 'numcols',
 'numrows',
 'project',
 's',
 'sigma',
 'standardize']

In [53]:
print results.Y

[[  7.84070175e-01   1.05108989e+00  -7.14839913e-01   1.08451570e+00
   -7.01848643e-01]
 [ -5.68396303e-01  -2.31789243e-01  -7.33540410e-01  -4.47110156e-01
   -2.75089301e-01]
 [  5.93608066e-01   4.77049753e-02   1.07108332e+00  -1.35053314e-02
    3.45149581e-03]
 [ -2.34360661e-01   1.59966660e+00   1.77043912e-01   1.05408155e+00
    2.70381146e-02]
 [ -7.75964899e-01  -1.39648497e+00  -9.67714918e-01   1.53213403e-01
   -5.62957031e-02]
 [  3.06833282e-01  -3.81994609e-01  -6.59125631e-01   1.96115013e-01
    6.57563969e-01]
 [ -1.49361274e+00   6.35436578e-02  -4.23079271e-02  -9.11775244e-01
    1.69233574e-01]
 [ -1.51809558e+00   9.93532208e-01  -4.87973741e-01   1.35470938e+00
    1.07674763e+00]
 [  2.15210334e+00   6.85789277e-02   5.67772080e-01  -1.55874986e-01
   -8.43784887e-01]
 [  4.21778547e-01   8.63791188e-01  -3.82823354e-01  -8.10675219e-01
   -8.64306722e-01]
 [  1.08801891e+00   3.92261402e-01  -4.71754910e-01  -3.17026967e-01
    1.49685107e-01]
 [ -1.7242

In [54]:
results.numcols

5

In [55]:
results.numrows

103

In [56]:
results.a

jp_morgan  citibank  wells_fargo     royal     exxon
0     0.575112 -0.405743    -0.321734 -1.816209  0.042516
1     0.356636  0.765469    -0.523603  0.294162  0.341528
2    -0.911745 -0.443756     0.561946 -0.150641 -0.367949
3     0.984674 -0.197713     1.056363 -1.214348 -0.397243
4     0.468876  0.146154    -0.785836  0.935325  1.334852
5     0.437591 -0.613648    -0.668387  0.359354 -0.037915
6     0.483592  1.305716     0.430719  0.985672 -0.029260
7     2.278022 -0.277071     1.110768  0.085035  0.131422
8    -1.708093 -0.690099    -0.646337 -1.263062 -0.536646
9    -0.274915  0.970743    -0.515190 -0.909366 -0.603753
10   -0.138519 -0.297099    -0.827544 -0.485092 -0.809641
11    0.662437  1.623874    -0.509597  1.199301  0.891356
12   -0.495091 -0.279692     0.206473  0.834935  0.322219
13   -2.254590 -1.359701    -1.062141  1.243652  1.053946
14   -1.225358 -0.904574     0.285902 -1.116336 -0.877167
15   -0.933791 -0.701070    -0.032740  0.122000 -0.497161
16   -1.481691 -1.389913    -1.208201  1.005814  0.448091
17   -1.132387 -1.123804     2.191479 -0.381324  0.098290
18    0.523606 -0.355541     1.133573 -0.871017 -0.700472
19    0.956916  1.116965     0.757233  1.171637  0.399611
20    0.519051  0.089631    -0.349444 -0.071822 -0.041930
21    0.622298  0.791102    -0.084485  0.407804  0.364025
22   -0.769315  0.119623    -0.120735  1.003973  0.672292
23    0.925741 -0.740501    -1.328824 -0.255863 -0.729380
24    0.488285 -1.089334    -0.453208 -1.070174  0.235261
25   -1.624457 -0.789824    -0.356040  0.382602  0.449241
26   -1.305526 -1.527502     0.934237 -0.059214  0.150945
27    0.826549  0.717616    -1.575602 -2.005109 -0.546772
28    1.005419  0.176084     0.803772  0.417287  0.639860
29   -1.642483 -1.006338    -0.786838 -0.843970 -1.068860
..         ...       ...          ...       ...       ...
73   -0.203971  0.051490    -0.153349  0.090779  0.631024
74    0.827505 -0.217221     0.204422  2.155733  1.413014
75   -0.735805 -0.539413    -1.054630 -0.144848 -1.773028
76   -0.273348 -0.838359     0.489661  1.302749 -0.044988
77   -0.399997  0.331205    -0.108654 -0.334541  0.527370
78    1.397091 -0.126524     1.636797 -1.293119 -0.899624
79   -0.392267 -2.088165    -1.297185 -2.080431  0.686863
80   -0.669623 -0.552041    -0.552709  0.470938 -0.602318
81    0.088196  0.114333    -0.600385  1.497646 -0.551940
82   -1.328475 -0.042459    -0.333822  2.139415  1.881782
83    0.277021  0.560747     0.399695 -1.713171 -1.467826
84   -1.297796 -1.178794    -2.137901 -0.929475 -0.394291
85    0.603466  0.839226     0.469468  1.964891  1.254352
86    0.953404  0.757018     0.487436 -1.006958  1.358592
87    0.187888  0.864363     0.050410  0.307143  0.137150
88   -1.309801 -0.245723    -1.219481 -0.509107 -0.071427
89   -0.252133  0.259495    -0.558188  0.350525 -0.311861
90    0.381622 -0.138340    -0.108654 -1.749545 -2.387408
91    0.206231 -0.428254     0.355534 -0.851076 -0.728054
92    1.427593 -0.799416     0.098787 -2.157680 -2.157491
93    1.742066  1.684016     1.580215  2.014144  0.467357
94    1.092481  0.117308    -0.568084  0.305268  0.872141
95    1.182785  2.476474     2.610611 -1.328585 -0.827111
96   -0.342298  0.380891     0.281659  1.507081  0.959692
97    0.993610  1.065097     1.842361  0.163337  1.007956
98    0.111036 -0.762047    -1.700594 -0.212912 -0.768522
99    0.110488  0.107239    -0.312500 -0.196003 -0.496521
100   0.766362  0.422556     1.107420 -0.752435 -0.419216
101   0.448237 -0.158345     0.187289 -0.242972 -0.740449
102  -0.665746 -0.717250    -1.360864 -0.335761 -0.737667

[103 rows x 5 columns]

In [57]:
results.mu

jp_morgan      0.001063
citibank       0.000655
wells_fargo    0.001626
royal          0.004049
exxon          0.004039
dtype: float64

In [58]:
results.fracs

array([ 0.48745462,  0.28140253,  0.10010255,  0.08000632,  0.05103398])

In [59]:
results.s

array([ 248.60185854,  143.51529123,   51.05230032,   40.80322182,
         26.02732808])

In [60]:
results_sk=sklearn.decomposition.PCA(n_components=None, copy=True, whiten=False)

AttributeError: 'module' object has no attribute 'decomposition'